### ISSUE TITLE
base64_encode is unsafe in multi-threaded environments

### ISSUE THREAD

**Issue by Yannic** [ReneNyffenegger/cpp-base64#15]
```c++
std::string base64_encode(
    unsigned char const* bytes_to_encode, unsigned int in_len, bool url) {
  if (url) {
    base64_chars[62] = '-';
    base64_chars[63] = '_';
  } else {
    base64_chars[62] = '+';
    base64_chars[63] = '/';
  }

  //...
}
```

If two threads call `base64_encode` concurrently (one with `url=true` and the other with `url=false`, the values of `base64_chars[62]` and `base64_chars[63]` are undefined. For example, it's possible to get `base64_chars[62]='-'` and `base64_chars[63]='/'`, which is not a valid encoding.

**Comment by ReneNyffenegger** [comment]
Fixed with https://github.com/ReneNyffenegger/cpp-base64/commit/ac7161c38ce855d9bb7a984358b16c2f28aaf3f1
