### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by egorpugin** [ReneNyffenegger/cpp-base64#16]
Hi, 

Could you create or push tags here, so releases will be visible?

**Comment by ReneNyffenegger** [comment]
I have created the tag "v2.rc.03". Is it this what you wanted?

**Comment by egorpugin** [comment]
Something like this, yes.
Maybe use semver like v2.0.3 for release?

**Comment by ReneNyffenegger** [comment]
I'll probably use semver when rc phase is over.
