### ISSUE TITLE
Question) module license and version

### ISSUE THREAD

**Issue by ipodipad** [ReneNyffenegger/cpp-base64#2]
Thanks for quick accepting of adding header guard issue :+1: 

I have two more questions

1) Can you explicitly add LICENSE or COPYING file to the top directory so that I can easily find out what kind of license this module is ( like MIT license or something..)
2) Can you add version to this module ? for example 1.0.0

**Comment by ipodipad** [comment]
@ReneNyffenegger 
Please answer for license.
:)

**Comment by ReneNyffenegger** [comment]
I've added a LICENSE file and the version in the files' top comment.

**Comment by ipodipad** [comment]
@ReneNyffenegger  Thank you :+1:
