### ISSUE TITLE
License under BSD 3-clause (or another established license)

### ISSUE THREAD

**Issue by appgurueu** [ReneNyffenegger/cpp-base64#44]
The license seems to be similar to [the 3-clause BSD license](https://opensource.org/license/bsd-3-clause/) in spirit, but not in exact wording.

Could you dual-license under your current license (for "backwards compatibility") and 3-clause BSD (or another established license you approve of)? This would help projects who want to be "on the safe side" licensing-wise.

**Comment by ndevenish** [comment]
In case anyone else sees the licence and doesn't recognise it, it's SPDX:[Zlib](https://spdx.org/licenses/Zlib.html)

**Comment by appgurueu** [comment]
I see, thanks. Would be good if the source code comment or readme mentioned this. It's a bit unfortunate that the license name is missing.
